### ISSUE TITLE
Aktion: Opencast Studio aktivieren

### ISSUE THREAD

**Issue by tthelen** [virtUOS/studip-tool-assistant#10]
In der Sektion "Online-Vorträge" -> "Podcasts und Videos selbst aufzeichnen" funktioniert der Aktionslink noch nicht.

Er soll:

1. Das Opencast-Plugin aktivieren
2. Sobald verfügbar: Opencast Studio aktivieren

**Comment by luniki** [comment]
Der erste Schritt ist mir klar.

Wie der zweite Schritt dann funktioniert, weiß ich leider nicht. Vllt kann @tgloeggl  helfen?

**Comment by tthelen** [comment]
Erledigt und funktioniert!
