### ISSUE TITLE
Aktion: Courseware einrichten

### ISSUE THREAD

**Issue by tthelen** [virtUOS/studip-tool-assistant#7]
In der Sektion "Lehrmaterialien verwenden" -> "Materialien zusammenstellen (Stud.IP: Courseware)" funktioniert der Aktionslink noch nicht.

Er soll:
1. Courseware und Vips aktivieren, wenn noch nicht aktiv.
2. Rons Beispiel-Courseware-Tutorial importieren

**Comment by rlucke** [comment]
Coureware und Vips aktivieren muss ich noch bauen!

**Comment by tthelen** [comment]
Funktioniert!
